[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/camallo/dkregistry-rs.git"]
git = "https://github.com/camallo/dkregistry-rs.git"
rev = "854d0da53bef5dd85b5e901123e85d43af97c74e"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
